### ISSUE TITLE
DPLA link match, false misses

### ISSUE THREAD

**Issue by ghukill** [WSULib/combine#157]
Guessing some special characters in an identifier like the following are resulting in a "miss" for the DPLA Bulk Data comparison:

```
mi--oai:michigan:rept2ic:oai:quod.lib.umich.edu:IC-REPT2IC-X-87%5DBOOK083_025
```

SQL comparisons, perhaps it's the percent sign `%`?

**Comment by colehudson** [comment]
and also uses `LIKE`, I believe

**Comment by ghukill** [comment]
Turns out, records were not actually *in* DPLA bulk data!  Bulk Data from 04/2018 did not include ingests from late April; confirmed with datastamps.  

Closing.
