### ISSUE TITLE
add XSD validation

### ISSUE THREAD

**Issue by ghukill** [WSULib/combine#289]
Schematron is currently supported, but add the arguably more common XSD (XML Schema Definition) validation as well.

**Comment by ghukill** [comment]
Added.  Using lxml to validate.  

Unfortunately, lxml appears to bail at the first exception, and doesn't appear possible to capture other, "down file" exceptions.  But, a step in the right direction, and scaffolding is there if another XSD validation approach is found.

![selection_001](https://user-images.githubusercontent.com/1753087/45856809-0e3ab180-bd24-11e8-830f-e21af8ff5466.png)

Closing.

**Comment by colehudson** [comment]
What about this one? https://github.com/brunato/xmlschema

**Comment by ghukill** [comment]
That was a good find, but as far as I can tell, still returns when the first error is met.
