### ISSUE TITLE
Redis-py out of date

### ISSUE THREAD

**Issue by dcmcand** [WSULib/combine#384]
On a brand new install, I get the following error at https://combine.example.com/combine/system. Updating requirements.txt to install redis 3.2.0 fixes this. 

Request Method: | GET
-- | --
https://combine.nhdiglib.org/combine/system
1.11.20
VersionMismatch
Redis transport requires redis-py versions 3.2.0 or later. You have 2.10.6
/usr/local/Miniconda3-4.3.30-Linux-x86_64/envs/combine/lib/python3.5/site-packages/kombu/transport/redis.py in _get_client, line 956
/usr/local/Miniconda3-4.3.30-Linux-x86_64/envs/combine/bin/python
3.5.5
['/opt/combine',  '/usr/local/Miniconda3-4.3.30-Linux-x86_64/envs/combine/bin',  '/usr/local/Miniconda3-4.3.30-Linux-x86_64/envs/combine/lib/python35.zip',  '/usr/local/Miniconda3-4.3.30-Linux-x86_64/envs/combine/lib/python3.5',  '/usr/local/Miniconda3-4.3.30-Linux-x86_64/envs/combine/lib/python3.5/plat-linux',  '/usr/local/Miniconda3-4.3.30-Linux-x86_64/envs/combine/lib/python3.5/lib-dynload',  '/usr/local/Miniconda3-4.3.30-Linux-x86_64/envs/combine/lib/python3.5/site-packages',  '/usr/local/Miniconda3-4.3.30-Linux-x86_64/envs/combine/lib/python3.5/site-packages/livy_python_api-0.5.0_incubating-py3.5.egg',  '/usr/local/Miniconda3-4.3.30-Linux-x86_64/envs/combine/lib/python3.5/site-packages/cryptography-2.6.1-py3.5-linux-x86_64.egg',  '/usr/local/Miniconda3-4.3.30-Linux-x86_64/envs/combine/lib/python3.5/site-packages/chardet-3.0.4-py3.5.egg',  '/usr/local/Miniconda3-4.3.30-Linux-x86_64/envs/combine/lib/python3.5/site-packages/cffi-1.12.2-py3.5-linux-x86_64.egg',  '/usr/local/Miniconda3-4.3.30-Linux-x86_64/envs/combine/lib/python3.5/site-packages/asn1crypto-0.24.0-py3.5.egg',  '/usr/local/Miniconda3-4.3.30-Linux-x86_64/envs/combine/lib/python3.5/site-packages/pycparser-2.19-py3.5.egg',  '/opt/combine']
Tue, 12 Mar 2019 00:09:51 +0000

**Comment by ghukill** [comment]
Good to know!  Thanks for the heads up.  Will try and release a version bump with this fix today.

**Comment by ghukill** [comment]
Is this on a [`v0.6`](https://github.com/WSULib/combine/releases/tag/v0.6) build?  Not that it matters per say, just curious.

**Comment by dcmcand** [comment]
@ghukill It was from master.

**Comment by ghukill** [comment]
Gotcha, good to know, thanks.

**Comment by ghukill** [comment]
Addressed in [`v0.6.1`](https://github.com/WSULib/combine/releases/tag/v0.6.1).  Closing.
